---
- hosts: all
  remote_user: root
  
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        udpate_cache: yes
    - name: Install latest version of "openjdk-8-jdk" ignoring "install-recommends"
      apt:
        name: "openjdk-8-jdk"
        state: latest
        install-recommends: no
    - name: Install git
      apt:
        name: "git"
        state: latest
        install-recommends: no
    - name: Remove useless packages from the udpate_cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
